[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "uva_common"
version = "0.1.0"
authors = [
    { name="Christopher W. Forstall", email="cforstall@mta.ca" },
    { name="Berenice Verhelst", email="b.verhelst@uva.nl" },
]
dependencies = [
    "lxml",
    "pandas",
    "gitpython",
    "osfclient",
]

[project.optional-dependencies]
nlp = ["spacy"]

[tool.setuptools.packages.find]
where = ["src"]
